name: poc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          project="PoCMobGen/Mobile Projects/New project"
          options="" # for instance {} 
          curl -fsSL https://raw.githubusercontent.com/mesopelagique/MobileBuildCmd/main/run.sh | bash -s ${{ secrets.SERVER_URL }} "$project" "$options"
